api:
  enabled: true
  address: '0.0.0.0:8686'

sources:
  docker:
    type: docker_logs
  vector_metrics:
    type: internal_metrics

transforms:
  msg_parser:
    type: remap
    inputs:
      - docker
    source: |-
      data, err = parse_json(.message)
      if err != null {
        .log = { "msg": .message }
      } else {
        .log = data
        .message = data.msg
      }
      del(.message)
          
sinks:
  vlogs:
    type: elasticsearch
    inputs:
      - msg_parser
    endpoints:
      - 'http://victorialogs:9428/insert/elasticsearch/'
    mode: bulk
    api_version: v8
    healthcheck:
      enabled: false
    query:
      _msg_field: log.msg
      _time_field: timestamp
      _stream_fields: 'host,container_name'

  victoriametrics:
    type: prometheus_remote_write
    endpoint: 'http://victoriametrics:8428/api/v1/write'
    inputs:
      - vector_metrics
    healthcheck:
      enabled: false