api:
  enabled: true
  address: '0.0.0.0:8686'

sources:
  docker:
    type: docker_logs
  caddy_metrics:
    type: prometheus_scrape
    endpoints:
      - http://caddy:2019/metrics
  vector_logs:
    type: internal_logs
  vector_metrics:
    type: internal_metrics

transforms:
  docker_msg_parser:
    type: remap
    inputs:
      - docker
    source: |-
      data, err = parse_json(.message)
      if err != null {
        .log = { "msg": .message }
      } else {
        .log = data
      }
      del(.message)
          
sinks:
  vlogs:
    type: elasticsearch
    inputs:
      - docker_msg_parser
    endpoints:
      - 'http://victorialogs:9428/insert/elasticsearch/'
    mode: bulk
    api_version: v8
    healthcheck:
      enabled: false
    query:
      _msg_field: log.msg
      _time_field: timestamp
      _stream_fields: 'host,container_name'

  vlogs:
    type: elasticsearch
    inputs:
      - vector_logs
    endpoints:
      - 'http://victorialogs:9428/insert/elasticsearch/'
    mode: bulk
    api_version: v8
    healthcheck:
      enabled: false
    query:
      _msg_field: message
      _time_field: timestamp
      _stream_fields: host

  caddymetrics:
    type: prometheus_remote_write
    endpoint: 'http://victoriametrics:8428/api/v1/write'
    inputs:
      - caddy_metrics
    healthcheck:
      enabled: false

  victoriametrics:
    type: prometheus_remote_write
    endpoint: 'http://victoriametrics:8428/api/v1/write'
    inputs:
      - vector_metrics
    healthcheck:
      enabled: false