api:
  enabled: true
  address: '0.0.0.0:8686'

sources:
  docker:
    type: docker_logs

  cadvisor:
    type: prometheus_scrape
    endpoints:
      - http://cadvisor:8080/metrics
  
  node_exporter:
    type: prometheus_scrape
    endpoints:
      - http://host.docker.internal:9100/metrics
  
  caddy_metrics:
    type: prometheus_scrape
    endpoints:
      - http://caddy:2019/metrics
  
  vector_logs:
    type: internal_logs

  vector_metrics:
    type: internal_metrics

transforms:
  docker_msg_parser:
    type: remap
    inputs:
      - docker
    source: |-
      data, err = parse_json(.message)
      if err == null {
        .message = data.msg
        del(data.msg)
        . = merge!(., data)
      }
          
sinks:
  vlogs:
    type: elasticsearch
    inputs:
      - vector_logs
      - docker_msg_parser
    endpoints:
      - 'http://victorialogs:9428/insert/elasticsearch/'
    mode: bulk
    api_version: v8
    healthcheck:
      enabled: false
    query:
      _msg_field: message
      _time_field: timestamp
      _stream_fields: 'host,container_name'

  victoriametrics:
    type: prometheus_remote_write
    endpoint: 'http://victoriametrics:8428/api/v1/write'
    inputs:
      - vector_metrics
      - cadvisor
      - node_exporter
      - caddy_metrics
    healthcheck:
      enabled: false