name: frontend

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v2.1.1@sha256:4fb41cb942d6f4f6e1facfe9425c80ca33cc4670db50b7c25b73a02d3b74eee5
    container_name: homepage
    volumes:
      - homepage_config:/app/config
      - /media/trinity:/trinity:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=mattvperry.com
      - HOMEPAGE_AUTH_ENABLED=true
      - HOMEPAGE_AUTH_SECRET=${HOMEPAGE_AUTH_SECRET}
      - HOMEPAGE_EXTERNAL_URL=https://mattvperry.com
      - HOMEPAGE_OIDC_ISSUER=https://auth.mattvperry.com
      - HOMEPAGE_OIDC_CLIENT_ID=86f0d165-8af6-479e-ba62-aeb51de93eda
      - HOMEPAGE_OIDC_CLIENT_SECRET=${HOMEPAGE_CLIENT_SECRET}
      - HOMEPAGE_OIDC_NAME=Carbon Auth
    networks:
      - default
      - media_default
      - pterodactyl_default
      - komodo_default
      - unifi_default
      - metrics_default
      - dns_default
      - auth_default
      - notifications_default
      - maintenance_default
      - pelican_default
      - books_default
    restart: unless-stopped

  ##
  # Reverse proxy
  ##
  proxy:
    image: docker.io/caddy:2.11.4@sha256:df7f1c2fb114453b951de51a98efc010db1655a92c2e86be6706714e2417a78d
    container_name: caddy
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - /srv:/srv
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
      - '9443:9443'
    networks:
      - default
      - media_default
      - pterodactyl_default
      - komodo_default
      - unifi_default
      - metrics_default
      - dns_default
      - auth_default
      - notifications_default
      - maintenance_default
      - pelican_default
      - trips_default
      - books_default
    restart: unless-stopped
    labels:
      - homepage.group=System
      - homepage.name=Caddy
      - homepage.icon=caddy
      - homepage.description=Reverse proxy
      - homepage.widget.type=caddy
      - homepage.widget.url=http://caddy:2019
    cap_add:
      - NET_ADMIN
networks:
  default:
  media_default:
    external: true
  pterodactyl_default:
    external: true
  komodo_default:
    external: true
  unifi_default:
    external: true
  metrics_default:
    external: true
  dns_default:
    external: true
  auth_default:
    external: true
  notifications_default:
    external: true
  maintenance_default:
    external: true
  pelican_default:
    external: true
  trips_default:
    external: true
  books_default:
    external: true

volumes:
  homepage_config:
  caddy_data:
  caddy_config:

