name: frontend

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.2@sha256:a0b71c8e757298d02560186bab9fbe3fc2d375c523a62cc1019177b37e48aa28
    container_name: homepage
    volumes:
      - homepage_config:/app/config
      - /media/trinity:/trinity:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=mattvperry.com
    networks:
      - default
      - media_default
      - pterodactyl_default
      - komodo_default
      - unifi_default
      - metrics_default
      - dns_default
      - auth_default
      - notifications_default
      - maintenance_default
      - pelican_default
      - books_default
    restart: unless-stopped

  ##
  # Reverse proxy
  ##
  proxy:
    image: docker.io/caddy:2.11.4@sha256:597f813aa60873d4c8148c816fbc4507d496ab160d620460279557f58ee3d0b9
    container_name: caddy
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - /srv:/srv
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
      - '9443:9443'
    networks:
      - default
      - media_default
      - pterodactyl_default
      - komodo_default
      - unifi_default
      - metrics_default
      - dns_default
      - auth_default
      - notifications_default
      - maintenance_default
      - pelican_default
      - trips_default
      - books_default
    restart: unless-stopped
    labels:
      - homepage.group=System
      - homepage.name=Caddy
      - homepage.icon=caddy
      - homepage.description=Reverse proxy
      - homepage.widget.type=caddy
      - homepage.widget.url=http://caddy:2019
    cap_add:
      - NET_ADMIN
networks:
  default:
  media_default:
    external: true
  pterodactyl_default:
    external: true
  komodo_default:
    external: true
  unifi_default:
    external: true
  metrics_default:
    external: true
  dns_default:
    external: true
  auth_default:
    external: true
  notifications_default:
    external: true
  maintenance_default:
    external: true
  pelican_default:
    external: true
  trips_default:
    external: true
  books_default:
    external: true

volumes:
  homepage_config:
  caddy_data:
  caddy_config:

