name: trips

services:
  trek:
    image: mauriceboe/trek:3.0.14@sha256:198c8dacba04a6c0a2aaccbdf802fa42c1220cfd32253ed5a0156cd177c64768
    container_name: trek
    environment:
      - APP_URL=https://trips.mattvperry.com
      - OIDC_ONLY=true
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - data:/app/data
      - uploads:/app/uploads
    restart: unless-stopped

volumes:
  data:
  uploads:
