name: trips

services:
  trek:
    image: mauriceboe/trek:3.0.7@sha256:0606a347ecb26138b2e8f9058e6784c62523df882387dd893a136bb26515ae46
    container_name: trek
    environment:
      - APP_URL=https://trips.mattvperry.com
      - OIDC_ONLY=true
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - data:/app/data
      - uploads:/app/uploads
    restart: unless-stopped

volumes:
  data:
  uploads:
