name: trips

services:
  trek:
    image: mauriceboe/trek:3.0.12@sha256:429ed7fd482350290793a9122610d94a26a45a13985b5d9d03dc473efd07f074
    container_name: trek
    environment:
      - APP_URL=https://trips.mattvperry.com
      - OIDC_ONLY=true
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - data:/app/data
      - uploads:/app/uploads
    restart: unless-stopped

volumes:
  data:
  uploads:
