name: komodo

services:
  core:
    image: ghcr.io/moghtech/komodo-core:2.3.1@sha256:768faad246f19f4c1ddfbb675346a7fe9a5010506d31ed4a21251199387004a2
    container_name: komodo_core
    init: true
    depends_on:
      - mongo
    volumes:
      - /etc/komodo/backups:/backups
      - keys:/config/keys
    environment:
      - TZ=America/New_York
      - KOMODO_DATABASE_ADDRESS=komodo_db:27017
      - KOMODO_DATABASE_USERNAME=${KOMODO_DB_USERNAME:-admin}
      - KOMODO_DATABASE_PASSWORD=${KOMODO_DB_PASSWORD}
      - KOMODO_HOST=https://docker.mattvperry.com
      - KOMODO_OIDC_ENABLED=true
      - KOMODO_OIDC_PROVIDER=https://auth.mattvperry.com
      - KOMODO_OIDC_CLIENT_ID=${KOMODO_OIDC_CLIENT_ID}
      - KOMODO_OIDC_CLIENT_SECRET=${KOMODO_OIDC_CLIENT_SECRET}
      - KOMODO_OIDC_USER_FULL_EMAIL=true
      - KOMODO_WEBHOOK_SECRET=${KOMODO_WEBHOOK_SECRET}
    restart: unless-stopped
    labels:
      - komodo.skip
      - homepage.group=System
      - homepage.name=Komodo
      - homepage.icon=komodo
      - homepage.href=https://docker.mattvperry.com
      - homepage.description=Docker management
      - homepage.widget.type=komodo
      - homepage.widget.url=https://docker.mattvperry.com
      - homepage.widget.key=${KOMODO_KEY}
      - homepage.widget.secret=${KOMODO_SECRET}
      - homepage.widget.showSummary=true

  mongo:
    image: mongo:8.3.7@sha256:a7f5aa200005611166adcec0192c2f11d0acc3bfd9d5eb68e1a998a990412e41
    container_name: komodo_db
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    environment:
      - TZ=America/New_York
      - MONGO_INITDB_ROOT_USERNAME=${KOMODO_DB_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${KOMODO_DB_PASSWORD}
      - GLIBC_TUNABLES=glibc.pthread.rseq=1
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    labels:
      - komodo.skip

  periphery:
    image: ghcr.io/moghtech/komodo-periphery:2.3.0@sha256:d5c1b59cad0875c4f08418bbfb465bf69694f3c37f97c6d036647477fbef729d
    container_name: komodo_periphery
    depends_on:
      - core
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo
      - keys:/config/keys
    environment:
      - TZ=America/New_York
      - PERIPHERY_CORE_ADDRESS=ws://komodo_core:9120
      - PERIPHERY_CONNECT_AS=Local
    restart: unless-stopped
    labels:
      - komodo.skip

volumes:
  mongo_data:
  mongo_config:
  keys:
