name: unifi

services:
  autocaliweb:
    image: gelbphoenix/autocaliweb:v0.12.12@sha256:b895a1685b59f3661aa70f3bb20f4051a95401c392661b97b03ed0917bf260db
    container_name: autocaliweb
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1001
    volumes:
      - autocaliweb_config:/config
      - bookdrop:/acw-book-ingest
      - /media/trinity/books:/calibre-library
    stop_signal: SIGINT
    stop_grace_period: 15s
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.35.1@sha256:1eef6716183c52abafe5405e7d6be8390248ecd59c7488c44af871757ac8fc4d
    container_name: audiobookshelf
    environment:
      - TZ=America/New_York
    volumes:
      - /media/trinity/audiobooks:/audiobooks
      - abs_config:/config
      - abs_metadata:/metadata
    restart: unless-stopped

  shelfmark:
    image: ghcr.io/calibrain/shelfmark:v1.3.2@sha256:8700c1d3b6bb94e1b5f9482bac12e39652ed737de02f256920e1ad982a7ac0f1
    container_name: shelfmark
    environment:
      - PUID=1000
      - PGID=1001
      - HIDE_LOCAL_AUTH=true
      - DISABLE_LOCAL_AUTH=true
      - OIDC_AUTO_REDIRECT=true
    volumes:
      - bookdrop:/bookdrop
      - shelfmark_config:/config
      - /media/trinity/audiobooks:/audiobooks
      - /media/trinity/.usenet/complete/books:/data/.usenet/complete/books
      - /media/trinity/.torrents/complete:/data/.torrents/complete
    networks:
      - default
      - media_default
    restart: unless-stopped

volumes:
  autocaliweb_config:
  abs_config:
  abs_metadata:
  shelfmark_config:
  bookdrop:

networks:
  default:
  media_default:
    external: true
