name: dns

services:
  technitium_dns:
    image: technitium/dns-server:15.2.0@sha256:23d3b63d959e997800b095fe93009b3fae271b5258234ff2ade8535cb33682c8
    container_name: technitium_dns
    volumes:
      - technitium_config:/etc/dns
    environment:
      - TZ=America/New_York
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=Technitium DNS
      - homepage.icon=technitium
      - homepage.href=https://dns.mattvperry.com
      - homepage.description=Network adblock
      - homepage.widget.type=technitium
      - homepage.widget.url=https://dns.mattvperry.com
      - homepage.widget.key=${TECHNITIUM_KEY}
      - homepage.widget.range=LastDay

volumes:
  technitium_config:
