name: dns

services:
  technitium_dns:
    image: technitium/dns-server:15.0.0@sha256:1265326d6744ba0ae24254c625196f2dfa84a36d4bb84dad07d9d2f950ace1d8
    container_name: technitium_dns
    volumes:
      - technitium_config:/etc/dns
    environment:
      - TZ=America/New_York
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=Technitium DNS
      - homepage.icon=technitium
      - homepage.href=https://dns.mattvperry.com
      - homepage.description=Network adblock
      - homepage.widget.type=technitium
      - homepage.widget.url=https://dns.mattvperry.com
      - homepage.widget.key=${TECHNITIUM_KEY}
      - homepage.widget.range=LastDay

volumes:
  technitium_config:
