name: dns

services:
  technitium_dns:
    image: technitium/dns-server:15.6.0@sha256:1045db38fd2f2e4d9578f9168b7eb4862575469ed0ffc79e03f36bdc772a93b5
    container_name: technitium_dns
    volumes:
      - technitium_config:/etc/dns
    environment:
      - TZ=America/New_York
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=Technitium DNS
      - homepage.icon=technitium
      - homepage.href=https://dns.mattvperry.com
      - homepage.description=Network adblock
      - homepage.widget.type=technitium
      - homepage.widget.url=https://dns.mattvperry.com
      - homepage.widget.key=${TECHNITIUM_KEY}
      - homepage.widget.range=LastDay

volumes:
  technitium_config:
