name: auth

services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.6.1@sha256:6111bc2d8c71932a71cb9a915506f57a83ba6c3a711931e50573ac26bcef154f
    container_name: pocketid
    volumes:
      - pocketid_data:/app/data
    environment:
      - APP_URL=https://auth.mattvperry.com
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - TRUST_PROXY=true
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v5.0.7@sha256:0793c71c49906e079d90c7e693cded9df569217a92d717dc9b171f2116fcd1c6
    container_name: tinyauth
    environment:
      - TINYAUTH_APPURL=https://authproxy.mattvperry.com
      - TINYAUTH_UI_TITLE=Proxy Auth
      - TINYAUTH_OAUTH_AUTOREDIRECT=pocketid
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID=${POCKETID_CLIENT_ID}
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET=${POCKETID_CLIENT_SECRET}
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL=https://auth.mattvperry.com/authorize
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL=https://auth.mattvperry.com/api/oidc/token
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL=https://auth.mattvperry.com/api/oidc/userinfo
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES=openid email profile groups
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME=Carbon Auth
    restart: unless-stopped

volumes:
  pocketid_data:
