name: auth

services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.4.0@sha256:3e790c5d4fd82ff276b1c2bc3242be9da13cff204a2b937768ea1eba1e892571
    container_name: pocketid
    volumes:
      - pocketid_data:/app/data
    environment:
      - APP_URL=https://auth.mattvperry.com
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - TRUST_PROXY=true
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v5.0.2@sha256:274c3b0f0e63457c9ded38fb855b5461788bac47e468be52f53d59c6c914593f
    container_name: tinyauth
    environment:
      - APP_URL=https://authproxy.mattvperry.com
      - APP_TITLE=Proxy Auth
      - OAUTH_AUTO_REDIRECT=pocketid
      - PROVIDERS_POCKETID_CLIENT_ID=${POCKETID_CLIENT_ID}
      - PROVIDERS_POCKETID_CLIENT_SECRET=${POCKETID_CLIENT_SECRET}
      - PROVIDERS_POCKETID_AUTH_URL=https://auth.mattvperry.com/authorize
      - PROVIDERS_POCKETID_TOKEN_URL=https://auth.mattvperry.com/api/oidc/token
      - PROVIDERS_POCKETID_USER_INFO_URL=https://auth.mattvperry.com/api/oidc/userinfo
      - PROVIDERS_POCKETID_SCOPES=openid email profile groups
      - PROVIDERS_POCKETID_NAME=Carbon Auth
    restart: unless-stopped

volumes:
  pocketid_data:
