name: media

services:
  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:3.0.1@sha256:91ea358e965c2693e18e1f21ce1e7df016610bfdfd50e94d1fa3cc8e5e1a53f4
    container_name: maintainerr
    volumes:
      - maintainerr_data:/opt/data
    environment:
      - TZ=Europe/Brussels
      - BASE_PATH=/maintain
    restart: unless-stopped
  nzbget:
    image: docker.io/linuxserver/nzbget:26.0.20260227@sha256:33e28111e4395227115002a39583a3bda36c4406ac126af32bffd5a2774d59fa
    container_name: nzbget
    volumes:
      - nzbget_config:/config
      - /media/trinity/.usenet:/data/.usenet
    environment:
      - PUID=974
      - PGID=1001
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - homepage.group=Downloads
      - homepage.name=NZBGet
      - homepage.icon=nzbget
      - homepage.href=https://mattvperry.com/nzb/
      - homepage.description=Usenet downloader
      - homepage.widget.type=nzbget
      - homepage.widget.url=http://nzbget:6789

  overseerr:
    image: docker.io/linuxserver/overseerr:1.35.0@sha256:6108ed066d4a919c05251d9dab041c1e55e67ff7247e7b31be97b65ffcbaeeb1
    container_name: overseerr
    volumes:
      - overseerr_config:/config
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Overseerr
      - homepage.icon=overseerr
      - homepage.href=https://media.mattvperry.com
      - homepage.description=Media requests
      - homepage.widget.type=overseerr
      - homepage.widget.url=http://overseerr:5055
      - homepage.widget.key=${OVERSEERR_API}

  plex:
    image: docker.io/linuxserver/plex:1.43.0@sha256:79dfc89947410ec120a3e34cf68f746f6f154de20772e6f27b9998ca9bd65a5e
    container_name: plex
    volumes:
      - plex_config:/config
      - /media/trinity:/data
    environment:
      - PUID=421
      - PGID=1001
      - TZ=America/New_York
      - VERSION=latest
    network_mode: host
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex
      - homepage.href=https://plex.mattvperry.com/
      - homepage.description=Media library
      - homepage.widget.type=plex
      - homepage.widget.url=https://plex.mattvperry.com
      - homepage.widget.key=${PLEX_API}
    devices:
      - /dev/dri:/dev/dri

  prowlarr:
    image: docker.io/linuxserver/prowlarr:2.3.0@sha256:a8fe7b9c502f979146b6d0f22438b825c38e068241bb8a708c473062dffdbb03
    container_name: prowlarr
    volumes:
      - prowlarr_config:/config
    environment:
      - PUID=977
      - PGID=977
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - homepage.group=Downloads
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr
      - homepage.href=https://mattvperry.com/index/
      - homepage.description=Usenet indexer
      - homepage.widget.type=prowlarr
      - homepage.widget.url=http://prowlarr:9696
      - homepage.widget.key=${PROWLARR_API}

  radarr:
    image: docker.io/linuxserver/radarr:6.0.4@sha256:a360633a3682d41e96f71a07ff36ecbdf2394a9628465b84b0a8437087715b41
    container_name: radarr
    volumes:
      - radarr_config:/config
      - /media/trinity:/data
    environment:
      - PUID=986
      - PGID=1001
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Radarr
      - homepage.icon=radarr
      - homepage.href=https://mattvperry.com/movies/
      - homepage.description=Movie management
      - homepage.widget.type=radarr
      - homepage.widget.url=http://radarr:7878
      - homepage.widget.key=${RADARR_API}
      - homepage.widget.enableQueue=true

  sonarr:
    image: docker.io/linuxserver/sonarr:4.0.16@sha256:37be832b78548e3f55f69c45b50e3b14d18df1b6def2a4994258217e67efb1a1
    container_name: sonarr
    volumes:
      - sonarr_config:/config
      - /media/trinity:/data
    environment:
      - PUID=991
      - PGID=1001
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr
      - homepage.href=https://mattvperry.com/tv/
      - homepage.description=Television management
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr:8989
      - homepage.widget.key=${SONARR_API}
      - homepage.widget.enableQueue=true

  tautulli:
    image: docker.io/linuxserver/tautulli:2.16.1@sha256:c75d3410b958399f86b6d1786f7640e91b867b24d154b3f09f9bb3207f2e8b35
    container_name: tautulli
    volumes:
      - tautulli_config:/config
    environment:
      - PUID=421
      - PGID=1001
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Tautulli
      - homepage.icon=tautulli
      - homepage.href=https://mattvperry.com/stats
      - homepage.description=Media statistics
      - homepage.widget.type=tautulli
      - homepage.widget.url=http://tautulli:8181/stats
      - homepage.widget.key=${TAUTULLI_API}

  transmission:
    image: docker.io/linuxserver/transmission:4.1.1@sha256:d2183a00bbd5dbb083b14dcd65419379bfd91e0965b52849642354ec3d246452
    container_name: transmission
    volumes:
      - transmission_config:/config
      - /media/trinity/.torrents:/data/.torrents
    environment:
      - PUID=169
      - PGID=1001
      - TZ=America/New_York
    ports:
      - '51413:51413'
      - '51413:51413/udp'
    restart: unless-stopped
    labels:
      - homepage.group=Downloads
      - homepage.name=Transmission
      - homepage.icon=transmission
      - homepage.href=https://mattvperry.com/torrent/web/
      - homepage.description=Torrent downloader
      - homepage.widget.type=transmission
      - homepage.widget.url=http://transmission:9091/
      - homepage.widget.rpcUrl=transmission/

volumes:
  transmission_config:
  nzbget_config:
  prowlarr_config:
  radarr_config:
  sonarr_config:
  tautulli_config:
  plex_config:
  overseerr_config:
  maintainerr_data:
