name: media

services:
  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:3.1.0@sha256:6c994bb7fd0dbe22deb008478bc6b35f2a8f2bb12412f6157a935d6c8842bd11
    container_name: maintainerr
    volumes:
      - maintainerr_data:/opt/data
    environment:
      - TZ=Europe/Brussels
      - BASE_PATH=/maintain
    restart: unless-stopped
  nzbget:
    image: docker.io/linuxserver/nzbget:26.0.20260306@sha256:ec3ef0ae7dc410084086a7fdd447deda4747531154aa1cc5c7c48ac60794e277
    container_name: nzbget
    volumes:
      - nzbget_config:/config
      - /media/trinity/.usenet:/data/.usenet
    environment:
      - PUID=974
      - PGID=1001
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - homepage.group=Downloads
      - homepage.name=NZBGet
      - homepage.icon=nzbget
      - homepage.href=https://mattvperry.com/nzb/
      - homepage.description=Usenet downloader
      - homepage.widget.type=nzbget
      - homepage.widget.url=http://nzbget:6789

  overseerr:
    image: docker.io/linuxserver/overseerr:1.35.0@sha256:6108ed066d4a919c05251d9dab041c1e55e67ff7247e7b31be97b65ffcbaeeb1
    container_name: overseerr
    volumes:
      - overseerr_config:/config
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Overseerr
      - homepage.icon=overseerr
      - homepage.href=https://media.mattvperry.com
      - homepage.description=Media requests
      - homepage.widget.type=overseerr
      - homepage.widget.url=http://overseerr:5055
      - homepage.widget.key=${OVERSEERR_API}

  plex:
    image: docker.io/linuxserver/plex:1.43.0@sha256:84f8646e799f6636876ab4f283d9fc8f6c51d56098ea74cba82bfb85074b68df
    container_name: plex
    volumes:
      - plex_config:/config
      - /media/trinity:/data
    environment:
      - PUID=421
      - PGID=1001
      - TZ=America/New_York
      - VERSION=latest
    network_mode: host
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex
      - homepage.href=https://plex.mattvperry.com/
      - homepage.description=Media library
      - homepage.widget.type=plex
      - homepage.widget.url=https://plex.mattvperry.com
      - homepage.widget.key=${PLEX_API}
    devices:
      - /dev/dri:/dev/dri

  prowlarr:
    image: docker.io/linuxserver/prowlarr:2.3.0@sha256:9ef5d8bf832edcacb6082f9262cb36087854e78eb7b1c3e1d4375056055b2d82
    container_name: prowlarr
    volumes:
      - prowlarr_config:/config
    environment:
      - PUID=977
      - PGID=977
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - homepage.group=Downloads
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr
      - homepage.href=https://mattvperry.com/index/
      - homepage.description=Usenet indexer
      - homepage.widget.type=prowlarr
      - homepage.widget.url=http://prowlarr:9696
      - homepage.widget.key=${PROWLARR_API}

  radarr:
    image: docker.io/linuxserver/radarr:6.0.4@sha256:ca43905eaf2dd11425efdcfe184892e43806b1ae0a830440c825cecbc2629cfb
    container_name: radarr
    volumes:
      - radarr_config:/config
      - /media/trinity:/data
    environment:
      - PUID=986
      - PGID=1001
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Radarr
      - homepage.icon=radarr
      - homepage.href=https://mattvperry.com/movies/
      - homepage.description=Movie management
      - homepage.widget.type=radarr
      - homepage.widget.url=http://radarr:7878
      - homepage.widget.key=${RADARR_API}
      - homepage.widget.enableQueue=true

  sonarr:
    image: docker.io/linuxserver/sonarr:4.0.16@sha256:21c1c3d52248589bb064f5adafec18cad45812d7a01d317472955eef051e619b
    container_name: sonarr
    volumes:
      - sonarr_config:/config
      - /media/trinity:/data
    environment:
      - PUID=991
      - PGID=1001
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr
      - homepage.href=https://mattvperry.com/tv/
      - homepage.description=Television management
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr:8989
      - homepage.widget.key=${SONARR_API}
      - homepage.widget.enableQueue=true

  tautulli:
    image: docker.io/linuxserver/tautulli:2.16.1@sha256:24594d6aed5f862f941349a6fa0d09d22d7a8386789aef954d3737c6b4dbb8c7
    container_name: tautulli
    volumes:
      - tautulli_config:/config
    environment:
      - PUID=421
      - PGID=1001
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Tautulli
      - homepage.icon=tautulli
      - homepage.href=https://mattvperry.com/stats
      - homepage.description=Media statistics
      - homepage.widget.type=tautulli
      - homepage.widget.url=http://tautulli:8181/stats
      - homepage.widget.key=${TAUTULLI_API}

  transmission:
    image: docker.io/linuxserver/transmission:4.1.1@sha256:25e04da44850ac03f93c9a2cfc4275c67ff0973e49eca48b459b06e0b45d7b82
    container_name: transmission
    volumes:
      - transmission_config:/config
      - /media/trinity/.torrents:/data/.torrents
    environment:
      - PUID=169
      - PGID=1001
      - TZ=America/New_York
    ports:
      - '51413:51413'
      - '51413:51413/udp'
    restart: unless-stopped
    labels:
      - homepage.group=Downloads
      - homepage.name=Transmission
      - homepage.icon=transmission
      - homepage.href=https://mattvperry.com/torrent/web/
      - homepage.description=Torrent downloader
      - homepage.widget.type=transmission
      - homepage.widget.url=http://transmission:9091/
      - homepage.widget.rpcUrl=transmission/

volumes:
  transmission_config:
  nzbget_config:
  prowlarr_config:
  radarr_config:
  sonarr_config:
  tautulli_config:
  plex_config:
  overseerr_config:
  maintainerr_data:
