name: pterodactyl

services:
  cron:
    image: ccarney16/pterodactyl-panel:v1.15.1@sha256:82407f6dbc259efc64619e4285d0a58089127ce777068913d21062b1cc0dfaee
    container_name: pterodactyl_cron
    volumes:
      - panel:/data
    env_file: ./panel.env
    command: p:cron
    restart: unless-stopped

  ##
  # -- Pterodactyl Daemon --
  # This service provides the wings runtime.
  ##
  daemon:
    image: docker.io/ccarney16/pterodactyl-daemon:v1.13.3@sha256:1ad8426ebf8686252c19f4854a838afa5295ab265729a17453607397a9dabfca
    container_name: pterodactyl_wings
    volumes:
      - /var/lib/pterodactyl:/var/lib/pterodactyl
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/pterodactyl:/tmp/pterodactyl
      - config:/etc/pterodactyl
    environment:
      - TZ=${DAEMON_TIMEZONE:-UTC}
    ports:
      - '2022:2022'
    restart: unless-stopped
    privileged: true

  ##
  # -- MariaDB --
  # Required for the control panel to work.
  # Stores Server/User information
  ##
  mariadb:
    image: mariadb:12.3.2@sha256:c237fd50cc48d6f2b87c4ca66d52f3b5eef7271b3bea7aee586c0be19d5b460d
    container_name: pterodactyl_db
    volumes:
      - mysql:/var/lib/mysql
    env_file: ./mariadb.env
    networks:
      default:
        aliases:
          - mysql
    restart: unless-stopped

  ##
  # -- Pterodactyl Panel --
  # This is the container that provides the main web interface.
  ##
  panel:
    image: ccarney16/pterodactyl-panel:v1.15.1@sha256:82407f6dbc259efc64619e4285d0a58089127ce777068913d21062b1cc0dfaee
    container_name: pterodactyl_panel
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - panel:/data
    env_file: ./panel.env
    restart: unless-stopped
    labels:
      - homepage.group=Games
      - homepage.name=Pterodactyl
      - homepage.icon=pterodactyl
      - homepage.href=https://games.mattvperry.com
      - homepage.description=Game server management
      - homepage.widget.type=pterodactyl
      - homepage.widget.url=https://games.mattvperry.com
      - homepage.widget.key=${PTERO_API_KEY}

  ##
  # -- Redis --
  ##
  redis:
    image: redis:8.10.0@sha256:344e3945a0b431c8ff1eecd58c5573538126bd756f02fc7e218ddf1fc2546366
    container_name: pterodactyl_cache
    networks:
      default:
        aliases:
          - cache
    restart: unless-stopped
    cpu_count: 2
    mem_limit: 128m

  ##
  # -- Panel Worker --
  ##
  worker:
    image: ccarney16/pterodactyl-panel:v1.15.1@sha256:82407f6dbc259efc64619e4285d0a58089127ce777068913d21062b1cc0dfaee
    container_name: pterodactyl_worker
    volumes:
      - panel:/data
    env_file: ./panel.env
    command: p:worker
    restart: unless-stopped

volumes:
  panel:
  mysql:
  config:
