services:
  watchtower:
    image: containrrr/watchtower
    command: --debug --http-api-update --http-api-periodic-polls --cleanup --remove-volumes
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8182:8080