services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: 
      - --http-api-update
      - --http-api-periodic-polls
      - --http-api-metrics
      - --cleanup
      - --remove-volumes
    environment:
      - WATCHTOWER_POLL_INTERVAL=43200
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8182:8080
    labels:
      - homepage.group=System
      - homepage.name=Watchtower
      - homepage.icon=watchtower
      - homepage.description=Docker updater
      - homepage.widget.type=watchtower
      - homepage.widget.url=http://watchtower:8080
      - homepage.widget.key=${WATCHTOWER_HTTP_API_TOKEN}