services:
  zfdash:
    image: docker.io/ad4mts/zfdash:latest
    container_name: zfdash
    ports:
      - 5001:5001
    privileged: true
    devices:
      - /dev/zfs:/dev/zfs
    volumes:
      - config:/root/.config/ZfDash
      - data:/opt/zfdash/data
    restart: unless-stopped

volumes:
  config:
  data: