name: maintenance

services:
  renovate:
    image: ghcr.io/mend/renovate-ce:14.5.0@sha256:7a985ff42ab9f513fe6ab559794fd8015c6ed4b1788cf51d48f42d4a2ebe6c42
    volumes:
      - ./config.js:/usr/src/app/config.js:ro
    environment:
      - LOG_LEVEL=debug
      - MEND_RNV_PLATFORM=github
      - MEND_RNV_GITHUB_APP_ID=${MEND_GITHUB_APP_ID}
      - MEND_RNV_GITHUB_APP_KEY=${MEND_GITHUB_APP_KEY}
      - MEND_RNV_WEBHOOK_SECRET=${MEND_WEBHOOK_SECRET}
      - MEND_RNV_LICENSE_KEY=${MEND_LICENSE_KEY}
      - MEND_RNV_ACCEPT_TOS=Y
    restart: unless-stopped
