name: maintenance

services:
  renovate:
    image: ghcr.io/mend/renovate-ce:14.4.0@sha256:f0fc4bb4beed5999230eb591b62fda8c002d42d7a5d48a0fe20265967a5fc054
    volumes:
      - ./config.js:/usr/src/app/config.js:ro
    environment:
      - LOG_LEVEL=debug
      - MEND_RNV_PLATFORM=github
      - MEND_RNV_GITHUB_APP_ID=${MEND_GITHUB_APP_ID}
      - MEND_RNV_GITHUB_APP_KEY=${MEND_GITHUB_APP_KEY}
      - MEND_RNV_WEBHOOK_SECRET=${MEND_WEBHOOK_SECRET}
      - MEND_RNV_LICENSE_KEY=${MEND_LICENSE_KEY}
      - MEND_RNV_ACCEPT_TOS=Y
    restart: unless-stopped
