name: maintenance

services:
  renovate:
    image: ghcr.io/mend/renovate-ce:15.0.0@sha256:f99e2702241daa15d6e9bcb08ef3db96079f9ab156cc951ca19cf592315eb16b
    volumes:
      - ./config.js:/usr/src/app/config.js:ro
    environment:
      - LOG_LEVEL=debug
      - MEND_RNV_PLATFORM=github
      - MEND_RNV_GITHUB_APP_ID=${MEND_GITHUB_APP_ID}
      - MEND_RNV_GITHUB_APP_KEY=${MEND_GITHUB_APP_KEY}
      - MEND_RNV_WEBHOOK_SECRET=${MEND_WEBHOOK_SECRET}
      - MEND_RNV_LICENSE_KEY=${MEND_LICENSE_KEY}
      - MEND_RNV_ACCEPT_TOS=Y
    restart: unless-stopped
