services:
  portainer:
    image: docker.io/portainer/portainer-ce:latest
    container_name: portainer
    command: --http-enabled
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9444:9443
    restart: always
    labels:
      - homepage.group=System
      - homepage.name=Portainer
      - homepage.icon=portainer
      - homepage.href=https://docker.mattvperry.com
      - homepage.widget.type=portainer
      - homepage.widget.env=2
      - homepage.widget.url=http://portainer:9000
      - homepage.widget.key=${PORTAINER_KEY}

volumes:
  portainer_data:
    external: true