name: unifi

services:
  orb-docker:
    image: orbforge/orb:1.5.5@sha256:ab4588af415f2d1fbcc6d33f30957bde2d3c57a41f6ce245d5560c6feba75ba2
    container_name: orb-sensor
    volumes:
      - orb_data:/root/.config/orb
    network_mode: host
    restart: unless-stopped

  unifi-os:
    image: ghcr.io/lemker/unifi-os-server:v1.6.0@sha256:1a6a7167082d005f714b33757af74972aeac890c156ea37136c863ca606bacf9
    container_name: unifi-os
    cgroup: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tmpfs:
      - /run:exec
      - /run/lock
      - /tmp:exec
      - /var/lib/journal
      - /var/opt/unifi/tmp:size=64m
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - unifi_os_persist:/persistent
      - unifi_os_log:/var/log
      - unifi_os_data:/data
      - unifi_os_srv:/srv
      - unifi_os_home:/var/lib/unifi
      - unifi_os_monogo:/var/lib/mongodb
      - unifi_os_rabbit:/etc/rabbitmq/ssl
    environment:
      - UOS_SYSTEM_IP=192.168.1.100
    ports:
      - '11443:443'
      - '3478:3478/udp'
      - '8080:8080'
      - '8443:8443'
      - '10003:10003/udp'
      - '10001:10001/udp'
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=Unifi
      - homepage.icon=unifi
      - homepage.href=https://unifi.mattvperry.com
      - homepage.description=Network management
      - homepage.widget.type=unifi
      - homepage.widget.url=https://unifi-os:443
      - homepage.widget.key=${UNIFI_API}
      - homepage.widget.fields=["uptime","wlan_devices"]

volumes:
  unifi_os_persist:
  unifi_os_log:
  unifi_os_data:
  unifi_os_srv:
  unifi_os_home:
  unifi_os_monogo:
  unifi_os_rabbit:
  orb_data:
