name: unifi

services:
  orb-docker:
    image: orbforge/orb:1.4.10@sha256:81413e01a7ea693c1d16a1b0891fba1f8278526397cd9b39b1e82f13b8c14413
    container_name: orb-sensor
    volumes:
      - orb_data:/root/.config/orb
    network_mode: host
    restart: unless-stopped

  unifi-os:
    image: ghcr.io/lemker/unifi-os-server:5.0.6@sha256:5e17e4492cca4ed5b821ea57c5cd51f524b46a25ee02c6b7a22a9a59807bd647
    container_name: unifi-os
    privileged: true
    volumes:
      - unifi_os_persist:/persistent
      - unifi_os_log:/var/log
      - unifi_os_data:/data
      - unifi_os_srv:/srv
      - unifi_os_home:/var/lib/unifi
      - unifi_os_monogo:/var/lib/mongodb
      - unifi_os_rabbit:/etc/rabbitmq/ssl
    environment:
      - UOS_SYSTEM_IP=192.168.1.100
    ports:
      - '11443:443'
      - '3478:3478/udp'
      - '8080:8080'
      - '8443:8443'
      - '10003:10003/udp'
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=Unifi
      - homepage.icon=unifi
      - homepage.href=https://unifi.mattvperry.com
      - homepage.description=Network management
      - homepage.widget.type=unifi
      - homepage.widget.url=https://unifi-os:443
      - homepage.widget.key=${UNIFI_API}
      - homepage.widget.fields=["uptime","wlan_devices"]

volumes:
  unifi_os_persist:
  unifi_os_log:
  unifi_os_data:
  unifi_os_srv:
  unifi_os_home:
  unifi_os_monogo:
  unifi_os_rabbit:
  mongo_db:
  orb_data: