name: pelican

services:
  panel:
    image: ghcr.io/pelican-dev/panel:v1.0.0-beta33@sha256:871032c289b7e00a23e1eb701772603750a14b8c7cfa72b072058ce645c41032
    container_name: pelican_panel
    volumes:
      - pelican_data:/pelican-data
    environment:
      - MAIL_DRIVER=log
      - APP_URL=https://pelican.mattvperry.com
      - APP_DEBUG=false
      - APP_ENV=production
      - XDG_DATA_HOME=/pelican-data
      - BEHIND_PROXY=true
      - TRUSTED_PROXIES=127.0.0.1
    restart: unless-stopped

  wings:
    image: ghcr.io/pelican-dev/wings:v1.0.0-beta24@sha256:2a1d4bbf7af43870d746684f8f8e01144cb6a0605bacab779fc1b2fda390591a
    restart: unless-stopped
    container_name: pelican_wings
    tty: true
    environment:
      - TZ=America/New_York
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/pelican:/var/lib/pelican
      - /tmp/pelican:/tmp/pelican
      - pelican_config:/etc/pelican

volumes:
  pelican_data:
  pelican_config:
