[api]
    enabled = true
    address = "0.0.0.0:8686"

# Docker logs -> Victoria logs

[sources.docker]
    type = "docker_logs"

[transforms.msg_parser]
    type = "remap"
    inputs = ["docker"]
    source = '''
    .log = parse_json!(.message)
    del(.message)
    '''

[sinks.vlogs]
    type = "elasticsearch"
    inputs = ["msg_parser"]
    endpoints = ["http://victorialogs:9428/insert/elasticsearch/"]
    mode = "bulk"
    api_version = "v8"
    healthcheck.enabled = false

    [sinks.vlogs.query]
        _msg_field = "log.msg"
        _time_field = "timestamp"
        _stream_fields = "host,container_name"

# Vector metrics -> Victoria metrics

[sources.vector_metrics]
    type = "internal_metrics"

[sinks.victoriametrics]
    type = "prometheus_remote_write"
    endpoint = "http://victoriametrics:8428/api/v1/write"
    inputs = ["vector_metrics"]
    healthcheck.enabled = false